project_id = "fyxiyevbbvidckzaequx"

[functions.lead-webhook]
verify_jwt = false

[functions.apple-wallet]
verify_jwt = false

[functions.google-wallet]
verify_jwt = false

[functions.generate-template]
verify_jwt = false

[functions.adaptive-template]
verify_jwt = false

[functions.generate-palette]
verify_jwt = false
