project_id = "fyxiyevbbvidckzaequx"

[functions.lead-webhook]
verify_jwt = true

[functions.apple-wallet]
verify_jwt = false

[functions.google-wallet]
verify_jwt = false

[functions.generate-template]
verify_jwt = true

[functions.adaptive-template]
verify_jwt = true

[functions.generate-palette]
verify_jwt = true

[functions.send-order-email]
verify_jwt = true

[functions.send-welcome-email]
verify_jwt = true

[functions.smart-suggestions]
verify_jwt = true

[functions.fetch-ical]
verify_jwt = false
